### ISSUE TITLE
table名は小文字で定義してください

### ISSUE THREAD

**Issue by ynaka6** [ishidapp/runapp#2]
https://github.com/ishidapp/runapp/blob/6e511ec33a8959a8476661fbc747d845fd812755/app/User.php#L40

以前Postgrasでエラーが出ていたかと思います。ここが原因と思われます。

**Comment by ishidapp** [comment]
@ynaka6 
ありがとうございます。
Record.phpの方も大文字になってしまっていたので、修正しました。
