### ISSUE TITLE
Modelのリレーション定義ではClassを指定する

### ISSUE THREAD

**Issue by ynaka6** [ishidapp/runapp#3]
https://github.com/ishidapp/runapp/blob/6e511ec33a8959a8476661fbc747d845fd812755/app/Record.php#L13

```
return $this->belongsTo(\App\User::class);
```

クラスを文字列ではなく、class定義にすることでIDEによってはクラスの定義をミスった時に「クラスが存在しない」のようなアラートで伝えてくれ事前にミスを防げます

**Comment by ishidapp** [comment]
@ynaka6 
ありがとうございます！
修正しました。
