### ISSUE TITLE
Recordモデルに$fillableを追加して、属性を明示する

### ISSUE THREAD

**Issue by ynaka6** [ishidapp/runapp#4]
https://github.com/ishidapp/runapp/blob/master/app/Record.php

$fillableを記載することで、fill関数を利用することができます。
そうするとcreate関数や`$model->fill()->save()`でのデータ登録/保存がシンプルにコーディングできるので、fillableを定義してみましょう。

またguardedを利用せずfillableで統一するのがいいと思います。
上述した通り、fillableでカラムを属性として定義することで、Modelを見るとどんな属性が存在するかわかります。tableのカラムを確認する必要もなくなるので手間も減ります。

**Comment by ishidapp** [comment]
@ynaka6 
ありがとうございます！
