### ISSUE TITLE
Recordモデルの登録方法をシンプルにする方法

### ISSUE THREAD

**Issue by ynaka6** [ishidapp/runapp#5]
Recordモデルに$fillableを追加して、属性を明示する #4
↑
モデルにfillableが定義されている前提となります。

https://github.com/ishidapp/runapp/blob/6e511ec33a8959a8476661fbc747d845fd812755/app/Http/Controllers/RecordController.php#L23-L27

```
$record = new Record();
$record->fill($request->validated() + ['user_id' => Auth::id() ])->save();

or 

Record::create($request->validated() + ['user_id' => Auth::id() ]);
```

**Comment by ynaka6** [comment]
編集処理も同じようにシンプルにできます。

https://github.com/ishidapp/runapp/blob/6e511ec33a8959a8476661fbc747d845fd812755/app/Http/Controllers/RecordController.php#L38-L40

**Comment by ishidapp** [comment]
@ynaka6 
ありがとうございます！
