### ISSUE TITLE
Carbonの日付生成について

### ISSUE THREAD

**Issue by ynaka6** [ishidapp/runapp#6]
https://github.com/ishidapp/runapp/blob/6e511ec33a8959a8476661fbc747d845fd812755/app/Http/Controllers/RecordController.php#L15

この部分なんですが、以下のようにシンプルに記載できそうです。

```
Carbon::today()->setDay($request->day)->format("Y-m-d");
```

**Comment by ishidapp** [comment]
@ynaka6 
ありがとうございます！修正したところ、同じ挙動になりました。
setDateメソッドはいくつか参考記事が見つかったのですが、setDayメソッドはどのように調べられたのでしょうか？

**Comment by ynaka6** [comment]
@ishidapp 
> ありがとうございます！修正したところ、同じ挙動になりました。
> setDateメソッドはいくつか参考記事が見つかったのですが、setDayメソッドはどのように調べられたのでしょうか？

setYearとかもあったと思ったので、setDayもあるでしょ。普通って感じでした 笑

**Comment by ynaka6** [comment]
https://carbon.nesbot.com/docs/
↑
公式を参考にしてみてください

**Comment by ishidapp** [comment]
@ynaka6 
ありがとうございます！
