### ISSUE TITLE
定数定義について

### ISSUE THREAD

**Issue by ynaka6** [ishidapp/runapp#9]
フレームワーク使ってるとdefineで定数定義することが無いですね。
https://github.com/ishidapp/runapp/blob/d0ad2a0042082f4191e2eed5d56968d849080d75/app/Http/Controllers/HomeController.php#L16

### [解決方法1]
constを利用する

```
class HomeController extends Controller
{
    private const DAYS_OF_WEEK = 7;

・・・
}
```

### [解決方法2]
Laravelのconfig機能を利用する。
以下のような`config/const.php`を作成します。

```
<?php

return [
    'days_of_week' => 7,
];
```
そうすると、`config('const.days_of_week')` で取得が可能です。

**Comment by ishidapp** [comment]
@ynaka6
ありがとうございます。
解決方法1で実装しました！
